# Generated by Django 2.2.2 on 2023-07-04 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reporter',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
