# Generated by Django 2.2.2 on 2023-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230704_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
